### ISSUE TITLE
Error installing aubio. Python not found

### ISSUE THREAD

**Issue by AnnaBronec** [georgbuechner/fast_bsg#13]
```
make[1]: Entering directory '/home/anna/fast_bsg'
mkdir deps
# Install aubio
wget -O deps/aubio-0.4.7.tar.bz2 https://aubio.org/pub/aubio-0.4.7.tar.bz2
--2021-10-03 15:12:58--  https://aubio.org/pub/aubio-0.4.7.tar.bz2
Resolving aubio.org (aubio.org)... 2001:41d0:2:7f1f::1, 94.23.252.31
Connecting to aubio.org (aubio.org)|2001:41d0:2:7f1f::1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 372173 (363K) [application/x-bzip2]
Saving to: ‘deps/aubio-0.4.7.tar.bz2’

deps/aubio-0.4.7.ta 100%[===================>] 363,45K  1,96MB/s    in 0,2s    

2021-10-03 15:12:58 (1,96 MB/s) - ‘deps/aubio-0.4.7.tar.bz2’ saved [372173/372173]

cd deps && tar xf aubio-0.4.7.tar.bz2
cd deps/aubio-0.4.7 && ./waf configure build
/usr/bin/env: ‘python’: No such file or directory
make[1]: *** [Makefile:6: audio] Error 127
make[1]: Leaving directory '/home/anna/fast_bsg'
make: *** [Makefile:28: install] Error 2
```

**Comment by georgbuechner** [comment]
I updated the title and put your bash-output in a code block. 

This should fix the problem. 
```alias python='python3'```

I will see whether I can make the installation work without manually having to do this. otherwise I'll add a notice in the README,md

**Comment by AnnaBronec** [comment]
Unfortunately I still have an error which you can see `below.`


`make audio
make[1]: Entering directory '/home/anna/fast_bsg'
mkdir deps
mkdir: cannot create directory ‘deps’: File exists
make[1]: *** [Makefile:2: audio] Error 1
make[1]: Leaving directory '/home/anna/fast_bsg'
make: *** [Makefile:28: install] Error 2`

**Comment by georgbuechner** [comment]
See my updated comment above.

**Comment by AnnaBronec** [comment]
I did a bit of research an this seems to be the solution:
```sudo ln -s /usr/bin/python3 /usr/bin/python```
